/**
 * Chat Exporter — Generates Markdown and PDF exports for AI chat messages.
 *
 * Reuses the same pdfkit setup and patterns as pdfExporter.ts.
 */

import PDFDocument from 'pdfkit'
import { createWriteStream } from 'fs'

// ─── Types ─────────────────────────────────────────────────────────────────

export interface ChatExportSource {
  id: string
  title: string
  snippet: string
  timestamp: string
  score: number
  sourceType: string
  sourceUrl: string | null
}

export interface ChatExportMessage {
  id: string | number
  role: 'user' | 'assistant' | 'system'
  content: string
  sources?: ChatExportSource[]
  confidence?: number
  createdAt: string
}

// ─── Helpers ───────────────────────────────────────────────────────────────

function formatDate(iso: string): string {
  try {
    const d = new Date(iso)
    return d.toISOString().replace('T', ' ').slice(0, 19) + ' UTC'
  } catch {
    return iso
  }
}

function formatNow(): string {
  const now = new Date()
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${pad(now.getHours())}:${pad(now.getMinutes())} UTC`
}

function formatNowFilename(): string {
  const now = new Date()
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`
}

function confidenceBar(pct: number): string {
  const filled = Math.round(pct / 10)
  const empty = 10 - filled
  return '█'.repeat(filled) + '░'.repeat(empty)
}

function confidenceColor(pct: number): string {
  if (pct >= 80) return '#22C55E' // green
  if (pct >= 60) return '#F59E0B' // amber
  return '#EF4444' // red
}

// ─── Single Message Markdown ───────────────────────────────────────────────

export function exportMessageMarkdown(
  content: string,
  sources: ChatExportSource[],
  confidence: number | undefined,
  query?: string,
  createdAt?: string
): string {
  const lines: string[] = []

  lines.push('## AI Analysis')
  lines.push('')

  if (query) {
    lines.push(`**Query:** ${query}`)
    lines.push('')
  }

  if (confidence !== undefined) {
    const pct = Math.round(confidence * 100)
    lines.push(`**Confidence:** ${pct}% ${confidenceBar(pct)}`)
    lines.push('')
  }

  lines.push(content)
  lines.push('')

  if (sources && sources.length > 0) {
    lines.push('**Sources:**')
    lines.push('')
    sources.forEach((src, i) => {
      const scorePct = Math.round(src.score * 100)
      const tag = src.sourceType ? ` [${src.sourceType}]` : ''
      lines.push(`${i + 1}. **${src.title}**${tag} (Score: ${scorePct}%)`)
      if (src.snippet) {
        lines.push(`   - ${src.snippet}`)
      }
      if (src.sourceUrl) {
        lines.push(`   - ${src.sourceUrl}`)
      }
      lines.push('')
    })
  }

  const ts = createdAt ? formatDate(createdAt) : formatNow()
  lines.push('---')
  lines.push(`*Generated by Intel Board AI • ${ts}*`)

  return lines.join('\n')
}

// ─── Single Message PDF ────────────────────────────────────────────────────

export async function exportMessagePdf(
  content: string,
  sources: ChatExportSource[],
  confidence: number | undefined,
  filePath: string,
  query?: string,
  createdAt?: string
): Promise<void> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'LETTER',
      margins: { top: 50, bottom: 50, left: 50, right: 50 }
    })

    const stream = createWriteStream(filePath)
    doc.pipe(stream)

    // Title
    doc.fontSize(18).font('Helvetica-Bold').text('AI Analysis', { align: 'center' })
    doc.moveDown(0.5)

    // Query
    if (query) {
      doc.fontSize(11).font('Helvetica-Oblique').text(`Query: ${query}`)
      doc.moveDown(0.3)
    }

    // Confidence bar
    if (confidence !== undefined) {
      const pct = Math.round(confidence * 100)
      const color = confidenceColor(pct)

      doc.fontSize(10).font('Helvetica').text(`Confidence: ${pct}%`, { continued: false })
      doc.moveDown(0.2)

      // Draw colored bar
      const barX = doc.x
      const barY = doc.y
      const barWidth = 200
      const barHeight = 8

      doc.save()
      doc.rect(barX, barY, barWidth, barHeight).fill('#E5E7EB')
      doc.rect(barX, barY, barWidth * (pct / 100), barHeight).fill(color)
      doc.restore()
      doc.fillColor('#000000')
      doc.y = barY + barHeight + 4
      doc.moveDown(0.5)
    }

    // Separator
    doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor('#4B5563').lineWidth(0.5).stroke()
    doc.moveDown(0.5)

    // Content
    doc.fontSize(10).font('Helvetica').text(content, { lineGap: 3 })
    doc.moveDown(1)

    // Sources
    if (sources && sources.length > 0) {
      doc.fontSize(12).font('Helvetica-Bold').text('Sources')
      doc.moveDown(0.3)

      sources.forEach((src, i) => {
        const scorePct = Math.round(src.score * 100)
        const tag = src.sourceType ? ` [${src.sourceType}]` : ''

        doc.fontSize(10).font('Helvetica-Bold').text(`${i + 1}. ${src.title}${tag}`, { indent: 0 })
        doc.fontSize(9).font('Helvetica').text(`   Score: ${scorePct}%`, { indent: 0 })

        if (src.snippet) {
          doc.fontSize(9).font('Helvetica').text(`   ${src.snippet}`, { indent: 0 })
        }
        if (src.sourceUrl) {
          doc.fontSize(8).font('Courier').text(`   ${src.sourceUrl}`, { indent: 0 })
        }
        doc.moveDown(0.3)
      })
    }

    // Footer
    doc.moveDown(1)
    doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor('#4B5563').lineWidth(0.5).stroke()
    doc.moveDown(0.3)
    const ts = createdAt ? formatDate(createdAt) : formatNow()
    doc.fontSize(8).font('Helvetica-Oblique').text(`Generated by Intel Board AI • ${ts}`, { align: 'center' })

    doc.end()
    stream.on('finish', resolve)
    stream.on('error', reject)
  })
}

// ─── Full Conversation Markdown ────────────────────────────────────────────

export function exportConversationMarkdown(messages: ChatExportMessage[]): string {
  const lines: string[] = []
  const now = new Date()
  const pad = (n: number) => String(n).padStart(2, '0')
  const dateStr = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`

  lines.push('# Intel Board — AI Conversation')
  lines.push('')
  lines.push(`**Date:** ${dateStr}`)
  lines.push(`**Messages:** ${messages.length}`)
  lines.push('')
  lines.push('---')
  lines.push('')

  messages.forEach((msg) => {
    if (msg.role === 'user') {
      lines.push('### User')
      lines.push('')
      lines.push(msg.content)
      lines.push('')
    } else if (msg.role === 'assistant') {
      const confPct = msg.confidence !== undefined ? Math.round(msg.confidence * 100) : null
      const confLabel = confPct !== null ? ` — Confidence: ${confPct}%` : ''
      lines.push(`### Assistant${confLabel}`)
      lines.push('')
      lines.push(msg.content)
      lines.push('')

      if (msg.sources && msg.sources.length > 0) {
        lines.push('**Sources:**')
        msg.sources.forEach((src, i) => {
          const scorePct = Math.round(src.score * 100)
          lines.push(`${i + 1}. **${src.title}** (${scorePct}%)`)
        })
        lines.push('')
      }
    }

    lines.push('---')
    lines.push('')
  })

  lines.push(`*Generated by Intel Board AI • ${formatNow()}*`)

  return lines.join('\n')
}

// ─── Full Conversation PDF ─────────────────────────────────────────────────

export async function exportConversationPdf(
  messages: ChatExportMessage[],
  filePath: string
): Promise<void> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'LETTER',
      margins: { top: 50, bottom: 50, left: 50, right: 50 }
    })

    const stream = createWriteStream(filePath)
    doc.pipe(stream)

    // Title
    doc.fontSize(18).font('Helvetica-Bold').text('Intel Board — AI Conversation', { align: 'center' })
    doc.moveDown(0.3)

    const now = new Date()
    const pad = (n: number) => String(n).padStart(2, '0')
    const dateStr = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`
    doc.fontSize(10).font('Helvetica').text(`Date: ${dateStr}  •  Messages: ${messages.length}`, { align: 'center' })
    doc.moveDown(0.5)

    doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor('#4B5563').lineWidth(1).stroke()
    doc.moveDown(0.5)

    messages.forEach((msg, idx) => {
      // Check if we need a new page
      if (doc.y > 640) {
        doc.addPage()
      }

      if (msg.role === 'user') {
        doc.fontSize(12).font('Helvetica-Bold').fillColor('#60A5FA').text('User')
        doc.fillColor('#000000')
        doc.moveDown(0.2)
        doc.fontSize(10).font('Helvetica').text(msg.content)
        doc.moveDown(0.5)
      } else if (msg.role === 'assistant') {
        const confPct = msg.confidence !== undefined ? Math.round(msg.confidence * 100) : null
        const confLabel = confPct !== null ? ` — Confidence: ${confPct}%` : ''
        doc.fontSize(12).font('Helvetica-Bold').fillColor('#34D399').text(`Assistant${confLabel}`)
        doc.fillColor('#000000')
        doc.moveDown(0.2)

        // Confidence bar
        if (confPct !== null) {
          const color = confidenceColor(confPct)
          const barX = doc.x
          const barY = doc.y
          const barWidth = 150
          const barHeight = 6
          doc.save()
          doc.rect(barX, barY, barWidth, barHeight).fill('#E5E7EB')
          doc.rect(barX, barY, barWidth * (confPct / 100), barHeight).fill(color)
          doc.restore()
          doc.fillColor('#000000')
          doc.y = barY + barHeight + 4
        }

        doc.fontSize(10).font('Helvetica').text(msg.content, { lineGap: 2 })
        doc.moveDown(0.3)

        if (msg.sources && msg.sources.length > 0) {
          doc.fontSize(9).font('Helvetica-Bold').text('Sources:')
          doc.moveDown(0.1)
          msg.sources.forEach((src, i) => {
            const scorePct = Math.round(src.score * 100)
            doc.fontSize(8).font('Helvetica').text(`  ${i + 1}. ${src.title} (${scorePct}%)`)
          })
          doc.moveDown(0.3)
        }
      }

      // Separator between messages
      if (idx < messages.length - 1) {
        doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor('#9CA3AF').lineWidth(0.5).stroke()
        doc.moveDown(0.5)
      }
    })

    // Footer
    doc.moveDown(1)
    doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor('#4B5563').lineWidth(0.5).stroke()
    doc.moveDown(0.3)
    doc.fontSize(8).font('Helvetica-Oblique').fillColor('#6B7280').text(`Generated by Intel Board AI • ${formatNow()}`, { align: 'center' })

    doc.end()
    stream.on('finish', resolve)
    stream.on('error', reject)
  })
}

// ─── Filename Helpers ──────────────────────────────────────────────────────

export function messageFilename(extension: 'md' | 'pdf'): string {
  return `ai-analysis-${formatNowFilename()}.${extension}`
}

export function conversationFilename(extension: 'md' | 'pdf'): string {
  return `intel-conversation-${formatNowFilename()}.${extension}`
}