/**
 * Markdown Exporter — Generates a well-formatted Markdown report from intel items.
 */

import type { IntelItem, IntelTier } from '../../../shared/types'

const TIER_EMOJI: Record<IntelTier, string> = {
  ALERT: '🚨',
  WATCH: '📡',
  CONTEXT: 'ℹ️'
}

const TIER_ORDER: Record<IntelTier, number> = {
  ALERT: 0,
  WATCH: 1,
  CONTEXT: 2
}

function sortByTierAndTime(items: IntelItem[]): IntelItem[] {
  return [...items].sort((a, b) => {
    const tierDiff = (TIER_ORDER[a.tier] ?? 9) - (TIER_ORDER[b.tier] ?? 9)
    if (tierDiff !== 0) return tierDiff
    return new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
  })
}

function formatDate(iso: string): string {
  try {
    const d = new Date(iso)
    return d.toISOString().replace('T', ' ').slice(0, 19) + ' UTC'
  } catch {
    return iso
  }
}

function formatNow(): string {
  const now = new Date()
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${pad(now.getHours())}:${pad(now.getMinutes())}`
}

function formatPeriodLabel(hoursBack: number | null): string {
  if (hoursBack === null) return 'All time'
  if (hoursBack <= 24) return 'Last 24 hours'
  if (hoursBack <= 168) return 'Last 7 days'
  if (hoursBack <= 720) return 'Last 30 days'
  return `Last ${hoursBack} hours`
}

function formatCoordinates(lat: number | null, lon: number | null): string | null {
  if (lat === null || lon === null) return null
  const latDir = lat >= 0 ? 'N' : 'S'
  const lonDir = lon >= 0 ? 'E' : 'W'
  return `${Math.abs(lat).toFixed(2)}°${latDir}, ${Math.abs(lon).toFixed(2)}°${lonDir}`
}

export interface ExportOptions {
  tier?: IntelTier | null
  hoursBack?: number | null
}

export function generateMarkdownReport(items: IntelItem[], options: ExportOptions): string {
  const sorted = sortByTierAndTime(items)
  const tierLabel = options.tier ? `${options.tier} tier` : 'All tiers'
  const periodLabel = formatPeriodLabel(options.hoursBack ?? null)
  const now = formatNow()

  const lines: string[] = [
    '# Intel Board Report',
    '',
    `**Generated:** ${now}`,
    `**Period:** ${periodLabel}`,
    `**Filter:** ${tierLabel}`,
    `**Total Items:** ${items.length}`,
    '',
    '---'
  ]

  for (const item of sorted) {
    const emoji = TIER_EMOJI[item.tier] ?? '•'
    const confidence = item.confidence !== null ? (item.confidence * 100).toFixed(0) + '%' : 'N/A'
    const coords = formatCoordinates(item.latitude, item.longitude)

    lines.push('')
    lines.push(`## ${emoji} ${item.tier} — ${item.title}`)
    lines.push('')
    lines.push(
      `**Region:** ${item.region ?? 'Unknown'} | **Confidence:** ${confidence} | **Time:** ${formatDate(item.created_at)}`
    )
    lines.push('')

    if (item.summary) {
      lines.push(item.summary)
      lines.push('')
    }

    if (item.analysis) {
      lines.push(item.analysis)
      lines.push('')
    }

    if (item.sources && item.sources.length > 0) {
      lines.push('**Sources:**')
      for (const source of item.sources) {
        lines.push(`- ${source}`)
      }
      lines.push('')
    }

    if (item.categories && item.categories.length > 0) {
      lines.push(`**Categories:** ${item.categories.join(', ')}`)
      lines.push('')
    }

    if (coords) {
      lines.push(`**Location:** ${coords}`)
      lines.push('')
    }

    lines.push('---')
  }

  lines.push('')
  lines.push('*Report generated by Intel Board*')
  lines.push('')

  return lines.join('\n')
}